- src/frameworks/web/components/atoms/Tag/Tag.stories.tsx
- src/frameworks/web/components/atoms/Tag/Tag.tsx
- src/interfaces/frameworks/web/components/atoms/Tag/ITag.ts
- src/theme.ts
- 태그 컴포넌트 추가
- 테마 컬러값 변경 (오타)
- 제플린에는 Label이라 명명되어 있지만 이전 작업(#1)에 이미 사용한 명칭이라 다시 네이밍했습니다.
- 디자이너님께서 컬러 수치값을 잘못작성하셨다고 하셔서 그사항도 수정했습니다.
> feat: 태그 컴포넌트 추가

- .storybook/main.js
- .storybook/preview-head.html
- package.json
- public/index.html
- src/frameworks/web/components/atoms/Button/Button.tsx
- src/frameworks/web/components/atoms/CheckBox/CheckBox.stories.tsx
- src/frameworks/web/components/atoms/CheckBox/CheckBox.tsx
- src/frameworks/web/components/atoms/ContentSwitcher/ContentSwitcher.stories.tsx
- src/frameworks/web/components/atoms/ContentSwitcher/ContentSwitcher.tsx
- src/interfaces/frameworks/web/components/atoms/Button/IButton.ts
- src/interfaces/frameworks/web/components/atoms/CheckBox/ICheckBox.ts
- src/interfaces/frameworks/web/components/atoms/ContentSwitcher/IContentSwitcher.ts
- yarn.lock
- 체크박스 컴포넌트 추가
- Content Switcher 컴포넌트 추가
> feat: 체크박스 / Content Switcher 컴포넌트 추가

- src/frameworks/web/components/atoms/Select/Select.stories.tsx
- src/frameworks/web/components/atoms/Select/Select.tsx
- src/interfaces/frameworks/web/components/atoms/Select/ISelect.ts
- Select 컴포넌트 추가
- onClick 관련해 temporary function을 연결해놓았는데 이렇게 해도 괜찮을지 궁금합니다.
> feat: Select 컴포넌트 추가

- src/frameworks/web/components/atoms/Dropdown/Dropdown.stories.tsx
- src/frameworks/web/components/atoms/Dropdown/Dropdown.tsx
- src/interfaces/frameworks/web/components/atoms/Dropdown/IDropdown.ts
- 드롭다운 컴포넌트 (Design Web Guide 4)를 추가했어요!
- 스토리북도 포함!
> feat: Dropdown 컴포넌트 추가

- .storybook/main.js
- package.json
- src/frameworks/web/components/atoms/ContentsBox/ContentsBox.stories.tsx
- src/frameworks/web/components/atoms/ContentsBox/ContentsBox.tsx
- src/frameworks/web/components/atoms/RadioButton/RadioButton.stories.tsx
- src/frameworks/web/components/atoms/RadioButton/RadioButton.tsx
- src/interfaces/frameworks/web/components/atoms/ContentsBox/IContentsBox.ts
- yarn.lock
- Contents Box 컴포넌트 구현
- 여러 배경에서 컴포넌트를 preview하기 위해 storybook Addon (Background) 를 추가하였습니다.
- Radio Button 컴포넌트 구현
> feat: Contents Box & Radio Button 컴포넌트 추가

- src/frameworks/web/components/atoms/Dropdown/Dropdown.tsx
- src/frameworks/web/components/atoms/SearchField/SearchField.stories.tsx
- src/frameworks/web/components/atoms/SearchField/SearchField.tsx
- src/interfaces/frameworks/web/components/atoms/RadioButton/IRadioButton.ts
- src/interfaces/frameworks/web/components/atoms/SearchField/ISearchField.ts
- Search 컴포넌트를 추가했어요! (Design Web Guide 6)
> feat: Search (검색용 입력 필드) 컴포넌트 추가

- src/frameworks/web/components/atoms/TextArea/TextArea.stories.tsx
- src/frameworks/web/components/atoms/TextArea/TextArea.tsx
- src/frameworks/web/components/atoms/TextField/TextField.stories.tsx
- src/frameworks/web/components/atoms/TextField/TextField.tsx
- src/interfaces/frameworks/web/components/atoms/TextArea/ITextArea.ts
- src/interfaces/frameworks/web/components/atoms/TextField/ITextField.ts
- TextArea, TextField 컴포넌트 추가
- TextArea의 스크롤바를 숨겨놨는데, [이전 Dropdown에서 스크롤바를 숨겨놓았기 때문에](https://github.com/somul-project/somul-system-frontend/pull/6#issuecomment-600106865) TextArea도 같이 숨겨놓았습니다.
> feat: TextArea, TextField 컴포넌트 추가

- src/frameworks/web/components/molecules/RadioGroup/RadioGroup.tsx
- tsconfig.json
- [이전 커밋](https://github.com/somul-project/somul-system-frontend/commit/0b0f4cddd00374225631c5f6e4f3cc618ceaac9c) (#1) 에서 잘못 설정된 tsconfig을 수정했습니다.
- 이 설정때문에 `yarn start` 명령어가 작동되지 않았습니다.
> fix: 잘못 설정된 tsconfig 수정 / 일부 코드 import 경로 수정

- src/App.tsx
- src/frameworks/web/components/atoms/CheckBox/CheckBox.tsx
- src/frameworks/web/components/atoms/Label/Label.stories.tsx
- src/frameworks/web/components/atoms/Label/Label.tsx
- src/interfaces/frameworks/web/components/atoms/Button/IButton.ts
- src/interfaces/frameworks/web/components/atoms/Label/ILabel.ts
- Label 컴포넌트에 하이라이트 기능을 추가했습니다.
- 기존 방식 (각각 라밸 컴포넌트 export)으론 구현이 어려울 것 같아 구조를 클래스로 변경했습니다.
- Label이 사용되는 다른 컴포넌트도 다 수정했습니다.
- 해당 PR 은 #20 번을 해결한 PR 입니다.
Closed #20.
> feat: Label에 하이라이트 기능 추가

- package.json
- src/App.tsx
- ie 환경에서 사이트가 작동되지 않는 오류를 수정했습니다.
- react-app-polyfill 패키지를 추가했습니다.
> fix: IE11에서 열리지 않는 오류 수정

- src/frameworks/web/components/atoms/ContentsBox/ContentsBox.tsx
- src/frameworks/web/components/molecules/DividedCard/DividedCard.stories.tsx
- src/frameworks/web/components/molecules/DividedCard/DividedCard.tsx
- src/frameworks/web/components/molecules/SingleCard/SingleCard.stories.tsx
- src/frameworks/web/components/molecules/SingleCard/SingleCard.tsx
- src/interfaces/frameworks/web/components/atoms/ContentsBox/IContentsBox.ts
- src/interfaces/frameworks/web/components/molecules/DividedCard/IDividedCard.ts
- src/interfaces/frameworks/web/components/molecules/SingleCard/ISingleCard.ts
- Single Card, Divided Card 컴포넌트를 추가했습니다.
- 일단 storybook에는 카드 안에 간단한 label이 들어갔을 때 모습을 구현해놨습니다. 틀만 구현해놓았기 때문에 이후 화면 구현 시 내용을 넣어 다시 storybook을 통해 테스트 할 예정입니다.
> feat: Single Card, Divided Card 컴포넌트 추가

- .eslintrc.json
- .gitignore
- src/frameworks/web/components/organisms/Header/Header.tsx
- src/frameworks/web/components/organisms/Landing/LandingBanner.tsx
- src/interfaces/frameworks/web/components/organisms/LandingBanner/ILandingBanner.ts
Navbar 상단에 고정 되도록 Header, LandingBanner component 수정했습니다.
- #28 번 이슈와 연관있음
- Navbar 상단 고정 되도록 변경
> fix: Navbar 상단 고정

- src/frameworks/web/components/atoms/Button/Button.tsx
- src/frameworks/web/components/atoms/CheckBox/CheckBox.tsx
- src/frameworks/web/components/atoms/ContentSwitcher/ContentSwitcher.tsx
- src/frameworks/web/components/atoms/ContentsBox/ContentsBox.tsx
- src/frameworks/web/components/atoms/Label/Label.tsx
- src/frameworks/web/components/atoms/RadioButton/RadioButton.tsx
- src/frameworks/web/components/atoms/SearchField/SearchField.tsx
- src/frameworks/web/components/atoms/Select/Select.tsx
- src/frameworks/web/components/atoms/SignButton/SignButton.tsx
- src/frameworks/web/components/atoms/Tag/Tag.tsx
- src/frameworks/web/components/atoms/TextArea/TextArea.tsx
- src/frameworks/web/components/atoms/TextField/TextField.tsx
- src/interfaces/frameworks/web/components/atoms/Button/IButton.ts
- src/interfaces/frameworks/web/components/atoms/Label/ILabel.ts
- Button
- CheckBox
- ContentSwitcher
- Label
- RadioButton
- #49 번 이슈와 연관있음
- Atom component들을 Fuctinoal Component로 변경
> Refactor: Atom component를 Functional Component로 변경

- src/serviceWorker.ts
- serviceWorker.ts에서 발생하는 Compile 에러를 해결했습니다.
> chore: serviceWorker.ts 컴파일 에러 해결

- src/frameworks/web/components/molecules/DividedCard/DividedCard.tsx
- src/frameworks/web/components/molecules/RadioGroup/RadioGroup.tsx
- src/frameworks/web/components/molecules/SingleCard/SingleCard.tsx
- src/interfaces/frameworks/web/components/molecules/SingleCard/ISingleCard.ts
- DividedCard
- RadioGroup
- SingleCard
- #49  번 이슈와 연관있음
- Molecule component들을 Fuctinoal Component로 변경
> Refactor: Molecule component를 Functional Component로 변경

- public/icon/x.svg
- src/frameworks/web/components/molecules/Modal/Modal.stories.tsx
- src/frameworks/web/components/molecules/Modal/Modal.tsx
- src/interfaces/frameworks/web/components/molecules/Modal/IModal.ts
> chore: Modal 컴포넌트 추가

- .github/workflows/ci.yml
- Github actions를 이용해 테스트코드를 확인하는 CI를 추가했습니다.
> chore: Github Actions CI 추가

- src/utils/validator.ts
- YouTube URL 검증하는 함수 추가
- #37  번 이슈와 연관있음
> feat: YouTube URL validator 추가

- src/frameworks/web/components/pages/SignIn/SignIn.tsx
- src/frameworks/web/components/pages/SignUp/SignUp.tsx
- src/frameworks/web/components/pages/SpeakerApply/SpeakerApply.tsx
- src/frameworks/web/components/pages/StatusPage/StatusPage.tsx
- 일부 화면에서 보여지는 내용의 높이가 짧아 footer가 화면 하단에 있지 않고 살짝 위에 있는 오류가 발생해 이를 수정했습니다.
- #61 번 이슈와 연관있음
Closed #61
> fix: 보여주는 화면의 높이가 짧을 경우 footer가 재 위치에 있지 않는 오류 수정

- src/assets/icon/play.svg
- src/frameworks/web/components/atoms/VideoButton/VideoButton.stories.tsx
- src/frameworks/web/components/atoms/VideoButton/VideoButton.tsx
- src/frameworks/web/components/organisms/StatusPage/StatusContent.tsx
- src/frameworks/web/components/pages/StatusPage/StatusPage.tsx
- src/interfaces/frameworks/web/components/atoms/VideoButton/IVideoButton.ts
- src/interfaces/frameworks/web/components/organisms/StatusPage/IStatusContent.ts
- status 페이지에서 신청 기록이 있을 경우 나오는 화면을 추가했습니다.
- 이 화면에 들어가는 비디오 버튼을 컴포넌트에 추가했습니다.
- 어디에서 데이터를 가져올지 몰라, 일단 지금은 임시 값을 텍스트로 넣어놨습니다. 혹시나 props로 빼야한다면 말해주시면 수정하겠습니다.
- #40 번 이슈와 연관있음
Closed #40
> feat: 신청현황 페이지에 '신청한 강연이 있을 경우' 뷰 디자인 구현

- package.json
- src/frameworks/web/components/organisms/Header/Header.tsx
- src/frameworks/web/components/organisms/Landing/LandingBanner.tsx
- src/frameworks/web/components/pages/Landing/Landing.tsx
- yarn.lock
- 헤더에 있는 두 메뉴 (소물이란? / 후원안내) 가 랜딩페이지가 아닌 다른 페이지에서 클릭시 작동하지 않은 오류를 수정했습니다.
- 헤더나 랜딩페이지에 있는 '자세히보기' 버튼 클릭시 스크롤이 비정상적인 위치로 되는 오류를 수정했습니다.
- scrollIntoView라는 함수를 사용했는데 IE에 대해서 추가기능이 작동하지 않아 polyfill하는 패키지를 추가해 사용했습니다.
- Page 컴포넌트인 Landing 컴포넌트를 함수형으로 수정했습니다.
- #49 번 이슈와 연관있음
> fix: 헤더 관련 오류 수정

- src/frameworks/web/components/molecules/Modal/Modal.stories.tsx
- src/frameworks/web/components/molecules/NavigationBar/NavigationBar.tsx
- src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
- src/frameworks/web/components/organisms/SignUp/SignUpComplete.tsx
- src/frameworks/web/components/organisms/SignUp/SignUpNow.tsx
- src/utils/routes.ts
- Modal이 개발되지 않아 alert로 대체하였던 코드를 모두 제거하고 수정했습니다.
- 대부분 경고와 알림관련 내용이였지만, NavigationBar에 있는 alert는 가리키는 페이지 미개발로 '추후 공개될 예정입니다'가 뜨는 경고창이였는데 이미 해당 페이지들이 개발되어 그쪽으로 이동하는 a태그를 추가했습니다.
- 추가적으로, Modal storybook에 이미지 사용 방식을 바꾸었습니다.
- #69 번 이슈와 연관있음
Closed #69
> chore: 프로젝트에서 사용되던 alert를 Modal로 변경 및 제거

- src/utils/validator.ts
> fix: YouTube Short URL 수정

- src/frameworks/web/components/organisms/Header/Header.tsx
- src/frameworks/web/components/organisms/SignIn/ForgotPassword.tsx
- feat: 세션에 따라 접근 가능한 페이지와 불가능한 페이지 관리
로그인 유무에 따라 접근 가능한 페이지와 불가능한 페이지가 나뉘는데 이를 관리해주는 기능을 추가했습니다.
> feat: 세션에 따라 접근 가능한 페이지와 불가능한 페이지 관리

- src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
> fix: 비밀번호 변경 ui 제거

- src/frameworks/web/components/molecules/LectureModal/LectureModal.stories.tsx
- src/frameworks/web/components/molecules/LectureModal/LectureModal.tsx
- src/interfaces/frameworks/web/components/molecules/LectureModal/ILectureModal.ts
- 강연 리스트에서 카드를 클릭했을 때 띄워지는 모달 컴포넌트를 추가했습니다.
- #90 번 이슈와 연관있음
Closed #90
> chore: LectureModal 컴포넌트 추가

- src/frameworks/web/components/organisms/SignIn/SignInCard.tsx
- 로그인 페이지가 제플린 디자인과 다른 점을 수정했습니다.
- #95 이슈와 연관있음
- 회원가입 텍스트를 추가해야하지만 일단 비밀번호 변경 로직이 추가되어있지 않아 비밀변호 변경 로직 추가 이후 회원가입 텍스트를 추가할 예정입니다.
> fix: 로그인 페이지 화면 구성 수정

- src/frameworks/web/components/organisms/Header/Header.tsx
- src/frameworks/web/components/organisms/Lecture/LectureList.tsx
- src/frameworks/web/components/pages/Lecture/Lecture.tsx
- src/interfaces/frameworks/web/components/organisms/Lecture/ILectureList.ts
- src/interfaces/service/graphql/query/ISession.ts
- src/service/graphql/query/Sessions.ts
- yarn.lock
- 강연 목록 비즈니스 로직을 추가했어요! 이제 서버에서 불러온답니당
- 강연 목록을 클릭하면 강연 세부정보가 나와요!
#91, #92 의 해결 PR 입니다!
Closed #91.
Closed #92.
> feat: 강연 목록 비즈니스 로직 추가
